---
development:
  cloud_name: thiago-sato
  api_key: '654376279694392'
  api_secret: YezZuMfgkNiSzNWUZjCLD6CFWkQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: thiago-sato
  api_key: '654376279694392'
  api_secret: YezZuMfgkNiSzNWUZjCLD6CFWkQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: thiago-sato
  api_key: '654376279694392'
  api_secret: YezZuMfgkNiSzNWUZjCLD6CFWkQ
  enhance_image_tag: true
  static_image_support: false
